#    Copyright 2013 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""Storage refactor

Revision ID: 1e2c38f575fb
Revises: 1fcb29d29e03
Create Date: 2013-07-02 22:43:00.844574

"""

# revision identifiers, used by Alembic.
revision = '1e2c38f575fb'
down_revision = '1fcb29d29e03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'test_sets',
        sa.Column('id', sa.String(length=128), nullable=False),
        sa.Column('description', sa.String(length=128), nullable=True),
        sa.Column('data', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'test_runs', sa.Column('external_id', sa.String(length=128),
                                          nullable=True))
    op.add_column(u'test_runs', sa.Column('stats', sa.Text(), nullable=True))
    op.add_column(u'tests', sa.Column('test_set_id', sa.String(length=128),
                                      nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tests', 'test_set_id')
    op.drop_column(u'test_runs', 'stats')
    op.drop_column(u'test_runs', 'external_id')
    op.drop_table('test_sets')
    ### end Alembic commands ###
