"""add_test_set_dependency

Revision ID: 28d398150448
Revises: 53af7c2d9ccc
Create Date: 2014-02-13 16:01:19.518128

"""

# revision identifiers, used by Alembic.
revision = '28d398150448'
down_revision = '53af7c2d9ccc'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sets', sa.Column('master_testset',
                                         sa.String(length=128), nullable=True))
    op.add_column('test_sets', sa.Column('slave_testset',
                                         sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sets', 'slave_testset')
    op.drop_column('test_sets', 'master_testset')
    ### end Alembic commands ###
