"""add title column

Revision ID: 3e45add6471
Revises: 1b28f7bc6476
Create Date: 2013-08-07 17:01:59.306413

"""

# revision identifiers, used by Alembic.
revision = '3e45add6471'
down_revision = '1b28f7bc6476'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('title', sa.String(length=512),
                                     nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'title')
    ### end Alembic commands ###
