heat_template_version: '2013-05-23'
description: |
  Template which creates two instances
parameters:
  InstanceType:
    type: string
  ImageId:
    type: string
resources:
  Server1:
    type: OS::Nova::Server
    properties:
      image: {get_param: ImageId}
      flavor: {get_param: InstanceType}
  Server2:
    type: OS::Nova::Server
    properties:
      image: {get_param: ImageId}
      flavor: {get_param: InstanceType}
outputs:
  server1:
    value:
      get_resource: Server1
  server2:
    value:
      get_resource: Server2
