heat_template_version: '2013-05-23'
description: |
  Template which creates single instance
parameters:
  InstanceType:
    type: string
  ImageId:
    type: string
resources:
  Server:
    type: OS::Nova::Server
    metadata:
      Name: ost1-test_heat
    properties:
      image: {get_param: ImageId}
      flavor: {get_param: InstanceType}