CELERY_ACCEPT_CONTENT = ["json"]

CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_RESULT_BACKEND = "amqp"
CELERY_IGNORE_RESULT = False

#enable tracking STARTED state of task
CELERY_TRACK_STARTED = True
