resources =\
    {'apt': {'file': ['sources.list',
                      'sources.list.d',
                      'preferences.d',
                      '99unauth',
                      '99unauth',
                      'configure-apt-proxy']},
     'cinder::api': {'package': ['cinder-api', 'python-keystone'],
                     'service': ['cinder-api']},
     'cinder::base': {'file': ['/etc/cinder/cinder.conf',
                               '/etc/cinder/api-paste.ini'],
                      'package': ['cinder-common']},
     'cinder::scheduler': {'package': ['cinder-scheduler'],
                           'service': ['cinder-scheduler']},
     'cinder::volume': {'package': ['cinder-volume'],
                        'service': ['cinder-volume']},
     'cinder::volume::iscsi': {'package': ['tgt'], 'service': ['tgt']},
     'cobbler::server': {'file': ['/etc/init.d/dnsmasq',
                                  '/etc/xinetd.conf',
                                  '/etc/cobbler/modules.conf',
                                  '/etc/cobbler/settings',
                                  '/etc/cobbler/dnsmasq.template',
                                  '/etc/cobbler/pxe/pxedefault.template'],
                         'package': ['cobbler',
                                     'cobbler-web',
                                     'dnsmasq',
                                     'xinetd',
                                     'tftp-server',
                                     'syslinux',
                                     'wget'],
                         'service': ['cobbler', 'apache2', 'xinetd', 'dnsmasq']},
     'galera': {'file': ['/etc/my.cnf',
                         '/etc/mysql',
                         '/etc/mysql/conf.d',
                         '/etc/mysql/conf.d/wsrep.cnf'],
                'package': ['wget',
                            'perl',
                            'libssl0.9.8',
                            'libaio1',
                            'mysql-server-wsrep',
                            'galera'],
                'service': ['mysql']},
     'git': {'package': ['git-core']},
     'git::gitosis': {'package': ['gitosis']},
     'glance': {'file': ['/etc/glance/'], 'package': ['glance']},
     'glance::api': {'file': ['/etc/glance/glance-api-paste.ini',
                              '/etc/glance/glance-cache.conf'],
                     'service': ['glance-api']},
     'glance::backend::file': {'file': ['/var/lib/glance/images/']},
     'glance::client': {'package': ['python-glance']},
     'glance::registry': {'file': ['/etc/glance/glance-registry.conf',
                                   '/etc/glance/glance-registry-paste.ini'],
                          'service': ['glance-registry']},
     'haproxy': {'file': ['/etc/haproxy/haproxy.cfg', '/var/lib/haproxy'],
                 'package': ['haproxy'],
                 'service': ['haproxy']},
     'haproxy::data': {'file': ['/var/run/haproxy.pid']},
     'horizon': {'file': ['/etc/openstack-dashboard/local_settings.py',
                          '/etc/apache2/apache2.conf',
                          '/etc/apache2/conf.d/openstack-dashboard.conf'],
                 'package': ['apache2',
                             'libapache2-mod-wsgi',
                             'openstack-dashboard'],
                 'service': ['apache2']},
     'keepalived::install': {'package': ['keepalived']},
     'keepalived::service': {'file': ['/etc/keepalived/keepalived.conf'],
                             'service': ['keepalived']},
     'keystone': {'file': ['/etc/keystone'],
                  'package': ['keystone'],
                  'service': ['keystone']},
     'keystone::python': {'package': ['python-keystone']},
     'lvm': {'package': ['lvm2']},
     'mcollective::client': {'file': ['/etc/mcollective/client.cfg'],
                             'package': [False]},
     'mcollective::rabbitmq': {'file': ['/etc/rabbitmq/enabled_plugins']},
     'memcached': {'file': ['/etc/memcached.conf'],
                   'package': ['memcached'],
                   'service': ['memcached']},
     'mmm::agent': {'file': ['/etc/mysql-mmm', '/etc/default/mysql-mmm-agent'],
                    'package': ['mysql-mmm-agent']},
     'mmm::common': {'package': ['mysql-mmm-common']},
     'mmm::monitor': {'file': ['/etc/mysql-mmm',
                               '/etc/default/mysql-mmm-monitor'],
                      'package': ['mysql-mmm-monitor']},
     'mysql': {'package': ['mysql-client']},
     'mysql::java': {'package': ['libmysql-java']},
     'mysql::python': {'package': ['python-mysqldb']},
     'mysql::ruby': {'package': ['libmysql-ruby', 'gem']},
     'mysql::server': {'package': ['mysql-server'], 'service': ['mysql']},
     'mysql::server::mysqltuner': {'file': ['/usr/bin/mysqltuner']},
     'nova': {'file': ['/etc/nova/nova.conf', '/etc/nova/api-paste.ini'],
              'package': ['python',
                          'python-greenlet',
                          'python-nova',
                          'nova-common']},
     'nova::api': {'package': ['nova-api'], 'service': ['nova-api']},
     'nova::cert': {'package': ['nova-cert'], 'service': ['nova-cert']},
     'nova::client': {'package': ['python-novaclient']},
     'nova::compute': {'package': ['nova-compute'], 'service': ['nova-compute']},
     'nova::compute::file_hack': {'file': ['/usr/lib/python2.7/dist-packages/nova/virt/libvirt/connection.py',
                                           '/usr/lib/python2.7/dist-packages/nova/rootwrap/compute.py']},
     'nova::compute::kvm': {'package': ['nova-compute-kvm']},
     'nova::compute::libvirt': {'package': ['nova-compute',
                                            'libvirt-bin'],
                                'service': ['libvirtd']},
     'nova::compute::xenserver': {'package': ['xenapi']},
     'nova::consoleauth': {'package': ['nova-consoleauth'],
                           'service': ['nova-consoleauth']},
     'nova::objectstore': {'package': ['nova-objectstore'],
                           'service': ['nova-objectstore']},
     'nova::scheduler': {'package': ['nova-scheduler'],
                         'service': ['nova-scheduler']},
     'nova::utilities': {'package': ['unzip',
                                     'screen',
                                     'parted',
                                     'curl',
                                     'euca2ools']},
     'nova::vncproxy': {'package': ['python-numpy', 'nova-novncproxy'],
                        'service': ['nova-novncproxy']},
     'nova::volume': {'package': ['nova-volume'], 'service': ['nova-volume']},
     'nova::volume::iscsi': {'package': ['tgt'], 'service': ['tgt']},
     'ntpd': {'package': ['openntpd'], 'service': ['openntpd']},
     'postgresql': {'package': ['postgresql-client']},
     'postgresql::server': {'package': ['postgresql'], 'service': ['postgresql']},
     'rabbitmq::repo::apt': {'package': ['rabbitmq-server']},
     'rabbitmq::server': {'file': ['/etc/rabbitmq',
                                   '/etc/rabbitmq/rabbitmq.config'],
                          'package': ['rabbitmq-server'],
                          'service': ['rabbitmq']},
     'rabbitmq::service': {'service': ['rabbitmq']},
     'ssh::client::config': {'file': ['/etc/ssh/ssh_config',
                                      '/etc/ssh/ssh_known_hosts']},
     'ssh::client::install': {'package': ['openssh-client']},
     'ssh::server::config': {'file': ['/etc/ssh/sshd_config']},
     'ssh::server::install': {'package': ['openssh-server']},
     'ssh::server::service': {'service': ['ssh']},
     'swift': {'file': ['/home/swift',
                        '/etc/swift',
                        '/var/run/swift',
                        '/etc/swift/swift.conf'],
               'package': ['swift']},
     'swift::dispersion': {'file': ['/etc/swift/dispersion.conf']},
     'swift::proxy': {'package': ['swift-proxy'], 'service': ['swift-proxy']},
     'swift::proxy::swauth': {'package': ['python-swauth']},
     'swift::storage::account': {'package': ['swift-account'],
                                 'service': ['swift-account']},
     'swift::storage::container': {'package': ['swift-container'],
                                   'service': ['swift-container']},
     'swift::storage::object': {'package': ['swift-object'],
                                'service': ['swift-object']},
     'swift::xfs': {'package': ['xfsprogs']},
     'xinetd': {'file': ['/etc/xinetd.conf'],
                'package': ['xinetd'],
                'service': ['xinetd']}}
